# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands:
    - npm

steps:
- task: Npm@1
  displayName: Install npm dependencies
  inputs:
    command: 'install'

- task: Npm@1
  displayName: Build application
  inputs:
    command: 'custom'
    customCommand: 'run build-prod'


